name: vulcan

on:
    workflow_run:
        workflows: [regression test]
        types: [completed]

jobs:
    auto-repair:
        runs-on: [self-hosted, linux, x64, test]
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
            - name: run vulcan action
              uses: Suresoft-GLaDOS/vulcan-action@main
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                path: vulcan_target
                validator: ALL
