name: vulcan runner

on:
    workflow_dispatch:

jobs:
    auto-repair:
        runs-on: self-hosted
        steps:
            - name: Checkout vulcan target
              uses: actions/checkout@v2
            - name: Run vulcan action
              uses: Suresoft-GLaDOS/vulcan-action@main
